export const data = [
	{
		title: '400 Mbps',
		img: '/img/b1.jpg',
		para: 'S/0 Costo de instalación (previa evaluación)',
		price: '#85.00',
		type: 'planeshogar',
		id: 1,
	},
	{
		title: 'Plan: Max Ilimitado 69.90',
		img: '/img/lm5.jpg',
		para: '20% X 3 meses',
		price: '#55.92',
		type: 'planpostpago',
		id: 2,
	},
	{
		title: 'Por S/5',
		img: '/img/dm1.jpg',
		para: 'Para acceder a este beneficio, acepta el mensaje que recibirás despues de hacer tu recarga.',
		price: '#5.0',
		type: 'planprepago',
		id: 3,
	},
	{
		title: 'Iphone 15',
		img: '/img/sm3.jpg',
		para: 'APPLE',
		price: '#3739.00',
		type: 'equipos',
		id: 4,
	},
	{
		title: '300 Mbps',
		img: '/img/b2.jpg',
		para: 'S/0 Costo de instalación (previa evaluación)',
		price: '#75.00',
		type: 'planeshogar',
		id: 5,
	},
	{
		title: 'Plan: Max Ilimitado 79.90',
		img: '/img/lm3.jpg',
		para: '20% X 3 meses',
		price: '#63.92',
		type: 'planpostpago',
		id: 6,
	},
	{
		title: 'Por S/7',
		img: '/img/dm3c.jpg',
		para: 'Para acceder a este beneficio, acepta el mensaje que recibirás despues de hacer tu recarga.',
		price: '#7.0',
		type: 'planprepago',
		id: 7,
	},
	{
		title: 'Galaxy S24 Ultra',
		img: '/img/sm2.jpg',
		para: 'SAMSUNG',
		price: '#6479.00',
		type: 'equipos',
		id: 8,
	},
	{
		title: '600 Mbps',
		img: '/img/b3.jpg',
		para: 'S/0 Costo de instalación (previa evaluación)',
		price: '#100.00',
		type: 'planeshogar',
		id: 9,
	},
	{
		title: 'Plan: Max Ilimitado 95.90',
		img: '/img/lm1.jpg',
		para: '20% X 3 meses',
		price: '#76.72',
		type: 'planpostpago',
		id: 10,
	},
	{
		title: 'Por S/10',
		img: '/img/dm4a.jpg',
		para: 'Para acceder a este beneficio, acepta el mensaje que recibirás despues de hacer tu recarga.',
		price: '#10.00',
		type: 'planprepago',
		id: 11,
	},
	{
		title: '14T',
		img: '/img/sm4.jpg',
		para: 'XIAOMI',
		price: '#2299.00',
		type: 'equipos',
		id: 12,
	},
];